# Generated by Django 5.0.7 on 2024-08-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipoApi', '0002_ipoinfo_gain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipoinfo',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
