# Generated by Django 5.0.7 on 2024-08-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipoApi', '0003_alter_ipoinfo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipoinfo',
            name='exchange',
            field=models.CharField(default='NSE', max_length=50),
        ),
    ]
