# Generated by Django 5.0.7 on 2024-08-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipoApi', '0004_ipoinfo_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipoinfo',
            name='company_logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='company_images/'),
        ),
        migrations.AddField(
            model_name='ipoinfo',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
