# Generated by Django 5.0.7 on 2024-08-08 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipoApi', '0006_alter_ipoinfo_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipoinfo',
            name='company_logo_path',
        ),
    ]
