# Generated by Django 5.1 on 2024-08-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipoApi', '0008_ipoinfo_company_logo_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipoinfo',
            name='company_logo_path',
            field=models.TextField(),
        ),
    ]
