# Generated by Django 5.1 on 2024-08-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipoApi', '0009_alter_ipoinfo_company_logo_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipoinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
